services:

  blog_database:
    env_file:
      - ./.env
    container_name: $DOCKER_BACKEND_DB_CONTAINER_NAME
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_DB
    ports:
      - $DATABASE_PORT:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "database",
          "-U",
          "user"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-app:
    build: .
    ports:
      - "$PORT:$PORT"
    depends_on:
      blog_database:
        condition: service_healthy

volumes:
  database-data:
    driver: local
    name: blog-database
