services:

  blog_database:
    env_file:
      - ./.env
    container_name: blog_db
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: $DATABASE_DB
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "database", "-U", "user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  flask-app:
    container_name: server
    build: .
    image: blog-flask-app
    ports:
      - "172.17.0.1:$PORT:3000"
    depends_on:
      blog_database:
        condition: service_healthy

volumes:
  database-data:
    driver: local
    name: blog-database
